### ISSUE TITLE
getPurchases crashing the app

### ISSUE THREAD

**Issue by rdoi** [myflashlab/inAppPayments-ANE#36]
App crashes (probably) on getPurchases, when having a permanent purchased item. 

Compile platfom: Adobe Air 25.0 Win10 x64
Testing device: Galaxy Tab3 7.0 (lt02wifi) [SMT210] 
Android Kitkat 4.4.2
Google Play Store: 7.6.08.N-all [0] [PR] 149245622

We started testing IAP on Android (not able to test in iOS yet), it all went as expected till we confirmed our first permanent purchase of one of our product.

After confirming the purchase the test app immediately crashed. After restarting it, it now crashed everytime it calls Billing.init(). We then tried clearing the cache, reinstalling the app, and also using another test user with no result. Now, the app is always crashing immediately on init.

After further investigation, we discovered that clearing the Google Play Store cache seems to avoid the immediate crash on Billing.init(), allowing us to enter further in the app. But it would crash when try to getPurchases(), and after that start crashing again on Billing.init(), forcing us to clear the play store cache again.

The stacktrace the device is reporting to our google dev console is always the same:
```
java.lang.IllegalArgumentException: com.doitflash.inAppBilling.utils.Base64DecoderException: Bad Base64 input character at 3: 46(decimal)
	at com.doitflash.inAppBilling.utils.Security.generatePublicKey(Security.java:100)
	at com.doitflash.inAppBilling.utils.Security.verifyPurchase(Security.java:69)
	at com.doitflash.inAppBilling.utils.IabHelper.queryPurchases(IabHelper.java:1016)
	at com.doitflash.inAppBilling.utils.IabHelper.queryInventory(IabHelper.java:599)
	at com.doitflash.inAppBilling.utils.IabHelper.queryInventory(IabHelper.java:576)
	at com.doitflash.inAppBilling.utils.IabHelper$2.run(IabHelper.java:695)
	at java.lang.Thread.run(Thread.java:841)
Caused by: com.doitflash.inAppBilling.utils.Base64DecoderException: Bad Base64 input character at 3: 46(decimal)
	at com.doitflash.inAppBilling.utils.Base64.decode(Base64.java:546)
	at com.doitflash.inAppBilling.utils.Base64.decode(Base64.java:474)
	at com.doitflash.inAppBilling.utils.Base64.decode(Base64.java:420)
	at com.doitflash.inAppBilling.utils.Security.generatePublicKey(Security.java:84)
	... 6 more
```

Additional note: This do not happen when testing with static products or with users without permanent purchases.

Also, the same behavior is observable with your demo app too. 
Is there a log anywhere else we could check to get more clues of what is happening? 
Because it all happens inside the ane, we can't debug it properly.

**Comment by rdoi** [comment]
Just found #15. Is this related?

**Comment by myflashlab** [comment]
The error message says that the Android billing API key cannot be read. Make sure you are passing the correct API key when initializing the ANE ```Billing.init("Android KEY from Google Play Console", ... ```

**Comment by myflashlab** [comment]
Let us know if the problem is fixed?
