### ISSUE TITLE
Android app crash bug

### ISSUE THREAD

**Issue by MaksBrainiac** [myflashlab/inAppPayments-ANE#4]
Steps to reproduce:
1) Open your-android-application
2)  Billing.doPayment
3) Androind payment confirmation window is appeared (with price and description)
4) Click device "HOME" button, run some apps (facebook, instagram, etc..)
5) Return to your-android-application
6) Message "application has stopped error".
7) If clicked OK -> again Message "application has stopped error".

**Comment by myflashlab** [comment]
Thanks a lot for reporting this. we will look into this and get back to you.

**Comment by myflashlab** [comment]
good finding. we were able to duplicate the problem on one of our devices. (Samsung Galaxy tab 2). you are probably receiving this error message in Android Studio logcat

```
04-02 10:33:21.122 29699-29699/? E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.doitflash.exInAppBilling/com.doitflash.inAppBilling.utils.MyPurchase}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1970)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
at android.app.ActivityThread.access$600(ActivityThread.java:128)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.doitflash.inAppBilling.utils.MyPurchase.onCreate(MyPurchase.java:37)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995) 
at android.app.ActivityThread.access$600(ActivityThread.java:128) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:4514) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:511) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557) 
at dalvik.system.NativeStart.main(Native Method) 
```

**The reason** is that when you take your Air app to background while the billing dialog is open and run other apps, Android OS will close down the background apps/activities if it runs out of RAM memory. So, your app closes but the global payment dialog is still open because it's another activity and when you run your app again, the already payment activity instance cannot link itself with the app because the app has been closed before. That's why you see the error.

**The solution** Please upgrade to V1.0.1 which we has released just a few minutes ego! we have fixed this problem. Please update us after testing the fixed version and tell us if you still have the problem?
