### ISSUE TITLE
Random Crashes on Android

### ISSUE THREAD

**Issue by leossmith** [myflashlab/inAppPayments-ANE#78]
I am running on the latest available ANEs. My app works as expected but I get some random crashes in the Billing ANE.

## Environment ##
* Android API Version: 56% Android 7, 24% Android 6, 13% Android 8, 7% Android 5 (37% of the total errors happen on Samsung devices. 17% on Huawei)
* iOS Version: N/A
* AIR SDK Version: 29 latest

## Problem Description ##

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
com.doitflash.inAppBilling.utils.IabHelper.queryPurchases (IabHelper.java:1034)
com.doitflash.inAppBilling.utils.IabHelper.queryInventory (IabHelper.java:644)
com.doitflash.inAppBilling.utils.IabHelper$2.run (IabHelper.java:747)
java.lang.Thread.run (Thread.java:762)
```
This affects a limited amount of users, but it is still a problem.

## Steps to Reproduce ##
Not sure how to reproduce as this is tracked using Firebase Crashlytics and doesn't happen on my testing devices.

**Comment by leossmith** [comment]
Bump. This continues to happen. 

![image](https://user-images.githubusercontent.com/4300876/42272065-a94e7906-7f8d-11e8-8709-9757767f2478.png)

**Comment by myflashlab** [comment]
Well, we couldn't duplicate the problem neither. However, based on the logs you posted, we have come up with this revised version. [inAppPayments.ane.zip](https://github.com/myflashlab/inAppPayments-ANE/files/2163227/inAppPayments.ane.zip). Please use it in your app and see if crash logs change in the next coming weeks?

This is a demo version of the ANE but considering that you need to test it on a live app, you surely need a version without the demo dialog thing. So, If you are already using ANELAB, you'll be fine as ANELAB will automatically remove the dialog when you compile your app. If you're not using ANELAB software, please email us while referring to this issue and ask for this test ANE but without the demo dialog. Let's work together and see why that weird crash is happening. Thanks.

**Comment by myflashlab** [comment]
thanks, email sent.

**Comment by ikuprin** [comment]
I'm using ANELAB for testing and creating manifests, but can not use it for compiling by several reasons, e.g. release builds I'm compiling by Jenkins (CI). Can I retrieve not demo ane on email?

Sincerly, ILLIA
info@playcus.com

**Comment by myflashlab** [comment]
@ikuprin I have already sent the email. Thanks.

**Comment by ikuprin** [comment]
Hum... The new pack of crashes...

1.
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.ievogames.superbingo/com.doitflash.inAppBilling.utils.MyPurchase}: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getBuyIntent(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
       at android.app.ActivityThread.access$1000(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getBuyIntent(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.doitflash.inAppBilling.utils.IabHelper.launchPurchaseFlow(IabHelper.java:468)
       at com.doitflash.inAppBilling.utils.IabHelper.launchPurchaseFlow(IabHelper.java:413)
       at com.doitflash.inAppBilling.utils.MyPurchase.onCreate(MyPurchase.java:225)
       at android.app.Activity.performCreate(Activity.java:6093)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
       at android.app.ActivityThread.access$1000(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```
2.
```
Fatal Exception: java.lang.IllegalArgumentException
       at com.adobe.fre.FREContext.dispatchStatusEventAsync(FREContext.java)
       at com.doitflash.inAppBilling.AirCommand$5.onQueryInventoryFinished(AirCommand.java:452)
       at com.doitflash.inAppBilling.utils.IabHelper$2$1.run(IabHelper.java:760)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

```
3.
```
java.lang.IllegalArgumentException: 
  at com.adobe.fre.FREContext.dispatchStatusEventAsync (Native Method)
  at com.doitflash.inAppBilling.AirCommand$4.onIabSetupFinished (AirCommand.java:368)
  at com.doitflash.inAppBilling.utils.IabHelper$1.onServiceConnected (IabHelper.java:285)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1516)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1544)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)

```

**Comment by ikuprin** [comment]
Damn.. Tomorrow I released application with ane from your email, but got the same crash as described at start of thread...

 CPH1701
6.0.1
 Jul 20, 2018, 7:35:00 AM

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
com.doitflash.inAppBilling.utils.IabHelper.queryPurchases (IabHelper.java:1035)
com.doitflash.inAppBilling.utils.IabHelper.queryInventory (IabHelper.java:644)
com.doitflash.inAppBilling.utils.IabHelper$2.run (IabHelper.java:748)
java.lang.Thread.run (Thread.java:818)
```

**Comment by leossmith** [comment]
I am still getting these crashes. Any update?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
